### ISSUE TITLE
Good work!

### ISSUE THREAD

**Issue by huixiancheng** [GuoPingPan/RPVNet#2]
厉害！非常棒的复现。
想问下有训练完 在验证集上试下精度吗？

**Comment by GuoPingPan** [comment]
> 厉害！非常棒的复现。 想问下有训练完 在验证集上试下精度吗？

不好意思，由于计算资源等问题还未进行测试。

**Comment by huixiancheng** [comment]
好的👌 可惜也没啥卡 不然可以跑一下
