### ISSUE TITLE
询问目前项目状态

### ISSUE THREAD

**Issue by S-kewen** [GuoPingPan/RPVNet#4]
首先非常作者的贡献，复现并不是一件容易的事！
请问目前项目状态如何，复现的结果与paper相差多少呢？谢谢

**Comment by GuoPingPan** [comment]
> 首先非常作者的贡献，复现并不是一件容易的事！ 请问目前项目状态如何，复现的结果与paper相差多少呢？谢谢

hello，感谢你的关注，抱歉回复地有点晚了，可能我近期还不推这个项目（夏令营做的Orz）
复现的几个还没有完成的点：
- 在 `range2point` 方面的hash加速是还没做的，可以参考SPVCNN里面对于 `voxel2point` 的方式进行优化，是要自己写cuda算子加速的
- 另外这个模型的可行性上我可能没有完全验证过，没有卡(哭)，希望是真实能work的

再次感谢你的关注，希望能保持交流，后续我的研究方向可能是和Robotics有关
