### ISSUE TITLE
您好，你使用的torchsparse version是哪个？我出现了下列错误

### ISSUE THREAD

**Issue by Shadow581** [GuoPingPan/RPVNet#6]
![1](https://github.com/GuoPingPan/RPVNet/assets/45356169/9d9e5b23-c558-4e30-8c4d-82d36d45750a)

**Comment by Shadow581** [comment]
我找到解决方案了，现在torchsparse把PointTensor删除了。解决方案如下：
1、https://github.com/mit-han-lab/torchsparse/issues/213
2、https://github.com/mit-han-lab/spvnas/blob/dev/torchsparsepp_backend/core/models/utils.py#L16

**Comment by GuoPingPan** [comment]
👍感谢你提供的解决方案，可能torchsparse更新了。
